name: cyberguard
description: An Account Manager, not a Password Manager!

# Package is private, as it is not a Flutter package per-se. It is a standalone
# mobile application.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ### SECURITY
  crypto: ^3.0.3
  base32: ^2.1.3

  ### UNIT TESTING
  meta: ^1.11.0
  clock: ^1.1.1 # Creates 'mockable' clock that can be manipulated in tests.

  ### UTILITY
  vector_math: ^2.1.4
  auto_size_text: ^3.0.0
  uuid: ^4.1.0
  url_launcher: ^6.1.10
  async: ^2.10.0
  messagepack: ^0.2.1
  shared_preferences: ^2.1.1
  mobile_scanner: ^4.0.0
  image_picker: ^1.0.4
  http: ^1.1.0
  html: ^0.15.3

  ### USER INTERFACE
  heroicons: ^0.10.0
  flex_color_scheme: ^7.0.5
  rive: ^0.12.4
  flare_flutter: ^3.0.2

  ### STATE MANAGEMENT
  get_it: ^7.4.1
  go_router: ^13.2.0
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.3.6

  ### PRODUCTION
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  # Load Material Design icons.
  uses-material-design: true

  # Load assets.
  assets:
    - res/flare/loader.flr
    - res/rive/cyberguard-loader.riv
    - assets/images/cg-icon.png
    - assets/images/cg-icon-fg.png

  # Add custom fonts.
  fonts:
    - family: "Source Sans Pro"
      fonts:
        - asset: "assets/fonts/SourceSansPro-Light.ttf"
          weight: 300
        - asset: "assets/fonts/SourceSansPro-LightItalic.ttf"
          weight: 300
          style: italic
        - asset: "assets/fonts/SourceSansPro-Regular.ttf"
        - asset: "assets/fonts/SourceSansPro-Italic.ttf"
          style: italic
        - asset: "assets/fonts/SourceSansPro-SemiBold.ttf"
          weight: 500
        - asset: "assets/fonts/SourceSansPro-SemiBoldItalic.ttf"
          weight: 500
          style: italic
        - asset: "assets/fonts/SourceSansPro-Bold.ttf"
          weight: 600
        - asset: "assets/fonts/SourceSansPro-BoldItalic.ttf"
          weight: 600
          style: italic
        - asset: "assets/fonts/SourceSansPro-Black.ttf"
          weight: 900
        - asset: "assets/fonts/SourceSansPro-BlackItalic.ttf"
          weight: 900
          style: italic

flutter_launcher_icons:
  image_path: "assets/images/cg-icon.png"

  ios: true
  remove_alpha_ios: true

  # Android has manual alterations. Set this to true if you wish to totally
  # replace the Android launcher icon and the relevant configuration.
  android: false
  min_sdk_android: 23
  adaptive_icon_background: "#8E61F0"
  adaptive_icon_foreground: "assets/images/cg-icon-fg.png"
