name: cyberguard
description: Helping Users to Help Themselves to Cyber Security

# Package is private, as it is not a Flutter package per-se. It is a standalone
# mobile application.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^6.0.1
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  # Load Material Design icons.
  uses-material-design: true

  # Add custom fonts.
  fonts:
    - family: "Source Sans Pro"
      fonts:
        - asset: "assets/fonts/SourceSansPro-Light.ttf"
          weight: 300
        - asset: "assets/fonts/SourceSansPro-LightItalic.ttf"
          weight: 300
          style: italic
        - asset: "assets/fonts/SourceSansPro-Regular.ttf"
        - asset: "assets/fonts/SourceSansPro-Italic.ttf"
          style: italic
        - asset: "assets/fonts/SourceSansPro-SemiBold.ttf"
          weight: 500
        - asset: "assets/fonts/SourceSansPro-SemiBoldItalic.ttf"
          weight: 500
          style: italic
        - asset: "assets/fonts/SourceSansPro-Bold.ttf"
          weight: 600
        - asset: "assets/fonts/SourceSansPro-BoldItalic.ttf"
          weight: 600
          style: italic
        - asset: "assets/fonts/SourceSansPro-Black.ttf"
          weight: 900
        - asset: "assets/fonts/SourceSansPro-BlackItalic.ttf"
          weight: 900
          style: italic


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
