name: cyberguard
description: Helping Users to Help Themselves to Cyber Security

# Package is private, as it is not a Flutter package per-se. It is a standalone
# mobile application.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ### STATE MANAGEMENT
  get_it: ^7.2.0
  go_router: ^6.0.1
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.1.3

  ### PRODUCTION
  flutter_launcher_icons: ^0.10.0
  package_info_plus: ^1.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  # Load Material Design icons.
  uses-material-design: true

  # Add custom fonts.
  fonts:
    - family: "Source Sans Pro"
      fonts:
        - asset: "assets/fonts/SourceSansPro-Light.ttf"
          weight: 300
        - asset: "assets/fonts/SourceSansPro-LightItalic.ttf"
          weight: 300
          style: italic
        - asset: "assets/fonts/SourceSansPro-Regular.ttf"
        - asset: "assets/fonts/SourceSansPro-Italic.ttf"
          style: italic
        - asset: "assets/fonts/SourceSansPro-SemiBold.ttf"
          weight: 500
        - asset: "assets/fonts/SourceSansPro-SemiBoldItalic.ttf"
          weight: 500
          style: italic
        - asset: "assets/fonts/SourceSansPro-Bold.ttf"
          weight: 600
        - asset: "assets/fonts/SourceSansPro-BoldItalic.ttf"
          weight: 600
          style: italic
        - asset: "assets/fonts/SourceSansPro-Black.ttf"
          weight: 900
        - asset: "assets/fonts/SourceSansPro-BlackItalic.ttf"
          weight: 900
          style: italic
